apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: kafka-external
  namespace: service-mesh
spec:
  hosts:
  - kafka.external
  ports:
  - number: 9092
    name: kafka
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: DNS
  endpoints:
  - address: host.docker.internal
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: kafka-external
  namespace: traceability
spec:
  hosts:
  - kafka.external
  ports:
  - number: 9092
    name: kafka
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: DNS
  endpoints:
  - address: host.docker.internal
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: kafka-external
  namespace: service-mesh
spec:
  host: kafka.external
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: kafka-external
  namespace: traceability
spec:
  host: kafka.external
  trafficPolicy:
    tls:
      mode: DISABLE