apiVersion: v1
kind: Namespace
metadata:
  name: service-mesh
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: service-mesh
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
  - port: 9092
    targetPort: 9093
    name: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: redis-external
  namespace: service-mesh
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
  - port: 6379
    targetPort: 6379
    name: redis