apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kafka-docker
  namespace: service-mesh
spec:
  hosts:
  - host.docker.internal
  ports:
  - number: 9092
    name: kafka
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kafka-docker-dr
  namespace: service-mesh
spec:
  host: host.docker.internal
  trafficPolicy:
    tls:
      mode: DISABLE
