apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: traceability
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
  - port: 9092
    targetPort: 9092
    name: kafka